#!/usr/bin/env bash
# Script to correct NGINX to listen on port 80 instead of port 8080
sed -i 's/listen 8080/listen 80/g' /etc/nginx/sites-enabled/default
sed -i 's/listen \[::\]:8080\listen \[::\]:80/g' /etc/nginx/sites-enabled/default
pgrep nginx -o > /run/nginx.pid
nginx -s reload
echo '' > /run/nginx.pid
