#!/usr/bin/env bash
# Script to correct NGINX to listen on port 80 instead of port 8080
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
